FROM golang:1.25-alpine AS builder
ARG VERSION=dev
ARG GIT_COMMIT=unknown
ARG GIT_BRANCH=unknown
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build \
    -ldflags="-s -w -X main.version=${VERSION} -X main.commit=${GIT_COMMIT} -X main.branch=${GIT_BRANCH}" \
    -o /madvisor ./cmd/madvisor/

FROM alpine:3.19
RUN apk add --no-cache ncurses
COPY --from=builder /madvisor /madvisor
ENV TERM=xterm-256color
ENTRYPOINT ["/madvisor"]
