FROM golang:1.25-alpine AS builder
ARG VERSION=dev
ARG GIT_COMMIT=unknown
ARG GIT_BRANCH=unknown
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build \
    -ldflags="-s -w -X main.version=${VERSION} -X main.commit=${GIT_COMMIT} -X main.branch=${GIT_BRANCH}" \
    -o /madvisor ./cmd/madvisor/

FROM alpine:3
RUN apk add --no-cache ncurses && \
    addgroup -g 10001 -S madvisor && adduser -u 10001 -S madvisor -G madvisor
COPY --from=builder /madvisor /madvisor
USER 10001:10001
ENV TERM=xterm-256color
ENTRYPOINT ["/madvisor"]
